"use client";

import { useMemo, useState } from "react";
import { BarChart3, Copy, Grip, LayoutDashboard, Maximize2, Plus, Settings2, Trash2 } from "lucide-react";
import type { BaseRecord, DashboardDefinition, DashboardPage, DashboardVisual, DashboardVisualKind, DataTable } from "@/domain/base";
import { createId } from "@/domain/base";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const visualTypes: Array<[DashboardVisualKind, string]> = [["kpi", "KPI card"], ["bar", "Bar chart"], ["donut", "Donut chart"], ["taskList", "Task list"], ["goalProgress", "Goal progress"], ["text", "Text box"]];

export function DashboardBuilder({ table, dashboards, activeDashboardId, activePageId, currentUser, onChange, onSelect }: {
  table: DataTable;
  dashboards: DashboardDefinition[];
  activeDashboardId: string;
  activePageId: string;
  currentUser: string;
  onChange: (dashboards: DashboardDefinition[]) => void;
  onSelect: (dashboardId: string, pageId: string) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [selectedVisualId, setSelectedVisualId] = useState<string>();
  const [filters, setFilters] = useState({ status: "", category: "", owner: "" });
  const dashboard = dashboards.find((item) => item.id === activeDashboardId) ?? dashboards[0];
  const page = dashboard.pages.find((item) => item.id === activePageId) ?? dashboard.pages[0];
  const records = useMemo(() => table.records.filter((record) => (!filters.status || record.values.status === filters.status) && (!filters.category || record.values.category === filters.category) && (!filters.owner || record.values.owner === filters.owner)), [filters, table.records]);
  const updateDashboard = (updater: (item: DashboardDefinition) => DashboardDefinition) => onChange(dashboards.map((item) => item.id === dashboard.id ? updater(item) : item));
  const updatePage = (updater: (item: DashboardPage) => DashboardPage) => updateDashboard((item) => ({ ...item, pages: item.pages.map((entry) => entry.id === page.id ? updater(entry) : entry) }));
  const updateVisual = (id: string, patch: Partial<DashboardVisual>) => updatePage((item) => ({ ...item, visuals: item.visuals.map((visual) => visual.id === id ? { ...visual, ...patch } : visual) }));
  const selectedVisual = page.visuals.find((item) => item.id === selectedVisualId);

  const createDashboard = () => { const name = window.prompt("Dashboard name", "New Dashboard")?.trim(); if (!name) return; const pageId = createId("dashboard-page"); const next = { id: createId("dashboard"), name, owner: currentUser, scope: "personal" as const, baseId: dashboard.baseId, defaultPageId: pageId, pages: [{ id: pageId, name: "Overview", order: 0, visuals: [] }] }; onChange([...dashboards, next]); onSelect(next.id, pageId); setEditing(true); };
  const createPage = () => { const name = window.prompt("Page name", "New Page")?.trim(); if (!name) return; const next = { id: createId("dashboard-page"), name, order: dashboard.pages.length, visuals: [] }; updateDashboard((item) => ({ ...item, pages: [...item.pages, next] })); onSelect(dashboard.id, next.id); };
  const renamePage = () => { const name = window.prompt("Rename page", page.name)?.trim(); if (name) updatePage((item) => ({ ...item, name })); };
  const duplicatePage = () => { const copy = { ...structuredClone(page), id: createId("dashboard-page"), name: `${page.name} copy`, order: dashboard.pages.length, visuals: page.visuals.map((visual) => ({ ...structuredClone(visual), id: createId("visual") })) }; updateDashboard((item) => ({ ...item, pages: [...item.pages, copy] })); onSelect(dashboard.id, copy.id); };
  const deletePage = () => { if (dashboard.pages.length === 1 || !window.confirm(`Delete dashboard page “${page.name}”?`)) return; const next = dashboard.pages.filter((item) => item.id !== page.id).map((item, order) => ({ ...item, order })); updateDashboard((item) => ({ ...item, pages: next, defaultPageId: item.defaultPageId === page.id ? next[0].id : item.defaultPageId })); onSelect(dashboard.id, next[0].id); };
  const addVisual = (kind: DashboardVisualKind) => { const fieldId = kind === "donut" ? "status" : kind === "bar" ? "category" : undefined; const visual: DashboardVisual = { id: createId("visual"), kind, title: visualTypes.find(([id]) => id === kind)?.[1] ?? "Visual", fieldId, aggregation: kind === "kpi" ? "count" : undefined, x: 0, y: page.visuals.length * 2, w: kind === "kpi" ? 3 : 6, h: kind === "kpi" ? 2 : 4 }; updatePage((item) => ({ ...item, visuals: [...item.visuals, visual] })); setSelectedVisualId(visual.id); };

  return <div className="dashboard-studio">
    <header className="dashboard-studio-header"><div><span>ANALYTICS LAYER</span><div><select aria-label="Dashboard" value={dashboard.id} onChange={(event) => { const next = dashboards.find((item) => item.id === event.target.value)!; onSelect(next.id, next.defaultPageId); }} >{dashboards.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><small>{dashboard.scope} · owned by {dashboard.owner}</small></div></div><div><Button variant="secondary" size="sm" onClick={createDashboard}><Plus size={14} /> Dashboard</Button><Button variant={editing ? "primary" : "secondary"} size="sm" onClick={() => { setEditing((value) => !value); setSelectedVisualId(undefined); }}><Settings2 size={14} /> {editing ? "Done editing" : "Edit dashboard"}</Button></div></header>
    <div className="dashboard-pagebar"><div>{[...dashboard.pages].sort((a, b) => a.order - b.order).map((item) => <button key={item.id} className={item.id === page.id ? "active" : ""} onClick={() => onSelect(dashboard.id, item.id)}>{item.name}{item.id === dashboard.defaultPageId && <i title="Default page" />}</button>)}<button className="add-dashboard-page" onClick={createPage}><Plus size={13} /> Page</button></div>{editing && <span><button onClick={renamePage}>Rename</button><button onClick={duplicatePage}>Duplicate</button><button disabled={dashboard.pages.length === 1} onClick={deletePage}>Delete</button><button onClick={() => updateDashboard((item) => ({ ...item, defaultPageId: page.id }))}>Set default</button></span>}</div>
    <section className="dashboard-slicers"><strong>Page filters</strong><FilterSelect label="Status" value={filters.status} records={table.records} fieldId="status" onChange={(status) => setFilters((current) => ({ ...current, status }))} /><FilterSelect label="Category" value={filters.category} records={table.records} fieldId="category" onChange={(category) => setFilters((current) => ({ ...current, category }))} /><FilterSelect label="Owner" value={filters.owner} records={table.records} fieldId="owner" onChange={(owner) => setFilters((current) => ({ ...current, owner }))} /><span>{records.length} matching tasks</span></section>
    <div className={cn("dashboard-workbench", editing && "editing")}>
      {editing && <aside className="visual-library"><header><LayoutDashboard size={16} /><span><strong>Add visual</strong><small>Drag-free responsive grid</small></span></header>{visualTypes.map(([kind, name]) => <button key={kind} onClick={() => addVisual(kind)}><BarChart3 size={15} /><span>{name}</span><Plus size={13} /></button>)}</aside>}
      <main className="dashboard-canvas">{page.visuals.map((visual) => <article key={visual.id} className={cn("dashboard-block", editing && "editable", selectedVisualId === visual.id && "selected")} style={{ gridColumn: `span ${Math.min(12, visual.w)}`, minHeight: visual.h * 54 }} onClick={() => editing && setSelectedVisualId(visual.id)}>{editing && <div className="block-controls"><Grip size={13} /><button aria-label="Duplicate visual" onClick={(event) => { event.stopPropagation(); updatePage((item) => ({ ...item, visuals: [...item.visuals, { ...visual, id: createId("visual"), title: `${visual.title} copy` }] })); }}><Copy size={12} /></button><button aria-label="Resize visual" onClick={(event) => { event.stopPropagation(); updateVisual(visual.id, { w: visual.w >= 12 ? 4 : visual.w + 2 }); }}><Maximize2 size={12} /></button><button aria-label="Delete visual" onClick={(event) => { event.stopPropagation(); updatePage((item) => ({ ...item, visuals: item.visuals.filter((entry) => entry.id !== visual.id) })); }}><Trash2 size={12} /></button></div>}<Visual visual={visual} records={records} /></article>)}{page.visuals.length === 0 && <div className="empty-dashboard-canvas"><LayoutDashboard size={28} /><strong>Build this dashboard page</strong><span>Add KPI cards, charts and task lists from the visual library.</span></div>}</main>
      {editing && selectedVisual && <aside className="visual-config"><header><Settings2 size={15} /><strong>Visual configuration</strong></header><label>Visual title<input value={selectedVisual.title} onChange={(event) => updateVisual(selectedVisual.id, { title: event.target.value })} /></label><label>Visual type<select value={selectedVisual.kind} onChange={(event) => updateVisual(selectedVisual.id, { kind: event.target.value as DashboardVisualKind })}>{visualTypes.map(([kind, name]) => <option key={kind} value={kind}>{name}</option>)}</select></label><label>Dimension<select value={selectedVisual.fieldId ?? ""} onChange={(event) => updateVisual(selectedVisual.id, { fieldId: event.target.value || undefined })}><option value="">None</option>{table.fields.map((field) => <option key={field.id} value={field.id}>{field.name}</option>)}</select></label><label>Aggregation<select value={selectedVisual.aggregation ?? "count"} onChange={(event) => updateVisual(selectedVisual.id, { aggregation: event.target.value as DashboardVisual["aggregation"] })}><option value="count">Count</option><option value="sum">Sum</option><option value="average">Average</option></select></label><small>Data source: {table.name}. Visuals store configuration only—never duplicate task data.</small></aside>}
    </div>
  </div>;
}

function FilterSelect({ label, value, records, fieldId, onChange }: { label: string; value: string; records: BaseRecord[]; fieldId: string; onChange: (value: string) => void }) { const options = [...new Set(records.map((record) => String(record.values[fieldId] ?? "")).filter(Boolean))].sort(); return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }

function Visual({ visual, records }: { visual: DashboardVisual; records: BaseRecord[] }) {
  const groups = visual.fieldId ? countBy(records, visual.fieldId) : [];
  const value = visual.aggregation === "average" && visual.fieldId ? Math.round(records.reduce((sum, record) => sum + Number(record.values[visual.fieldId!] ?? 0), 0) / Math.max(1, records.length)) : visual.aggregation === "sum" && visual.fieldId ? Math.round(records.reduce((sum, record) => sum + Number(record.values[visual.fieldId!] ?? 0), 0)) : records.length;
  if (visual.kind === "kpi") return <div className="builder-kpi"><span>{visual.title}</span><strong>{value}{visual.aggregation === "average" && visual.fieldId === "progress" ? "%" : ""}</strong><small>Live from current Task Base slice</small></div>;
  if (visual.kind === "taskList") return <div className="builder-task-list"><header><strong>{visual.title}</strong><span>{records.length} tasks</span></header>{[...records].sort((a, b) => String(a.values.dueDate ?? "9999").localeCompare(String(b.values.dueDate ?? "9999"))).slice(0, 6).map((record) => <div key={record.id}><strong>{String(record.values.taskName ?? "Untitled")}</strong><span>{String(record.values.owner ?? "Unassigned")}</span><span>{String(record.values.status ?? "Not Started")}</span><time>{String(record.values.dueDate ?? "—").slice(0, 10)}</time></div>)}</div>;
  if (visual.kind === "text") return <div className="builder-text"><strong>{visual.title}</strong><p>Add context, insight or an executive narrative for this report page.</p></div>;
  if (visual.kind === "goalProgress") return <div className="builder-bars"><header><strong>{visual.title}</strong><span>Average task progress</span></header>{countAverage(records, "category", "progress").slice(0, 6).map((item) => <div key={item.label}><span>{item.label}</span><i><b style={{ width: `${item.value}%` }} /></i><strong>{item.value}%</strong></div>)}</div>;
  if (visual.kind === "donut") { const total = Math.max(1, records.length); const colors = ["#5b6ff2", "#15a37d", "#e6a23c", "#d95c5c", "#7b61a8", "#4c95b5"]; const segments = groups.map((item, index) => { const start = groups.slice(0, index).reduce((sum, entry) => sum + entry.count, 0) / total * 360; const end = start + item.count / total * 360; return `${colors[index % colors.length]} ${start}deg ${end}deg`; }); const background = segments.length ? `conic-gradient(${segments.join(",")})` : "#e5e7eb"; return <div className="builder-donut"><header><strong>{visual.title}</strong><span>COUNT by {visual.fieldId ?? "field"}</span></header><div><i style={{ background }}><b>{records.length}</b></i><span>{groups.slice(0, 6).map((item, index) => <small key={item.label}><i style={{ background: colors[index % colors.length] }} />{item.label}<b>{item.count}</b></small>)}</span></div></div>; }
  const maximum = Math.max(1, ...groups.map((item) => item.count)); return <div className="builder-bars"><header><strong>{visual.title}</strong><span>COUNT by {visual.fieldId ?? "field"}</span></header>{groups.slice(0, 7).map((item) => <div key={item.label}><span>{item.label}</span><i><b style={{ width: `${item.count / maximum * 100}%` }} /></i><strong>{item.count}</strong></div>)}</div>;
}

function countBy(records: BaseRecord[], fieldId: string) { const counts = new Map<string, number>(); records.forEach((record) => { const value = String(record.values[fieldId] ?? "Unassigned"); counts.set(value, (counts.get(value) ?? 0) + 1); }); return [...counts].map(([label, count]) => ({ label, count })).sort((a, b) => b.count - a.count); }
function countAverage(records: BaseRecord[], groupField: string, valueField: string) { const groups = new Map<string, number[]>(); records.forEach((record) => { const label = String(record.values[groupField] ?? "Unassigned"); groups.set(label, [...(groups.get(label) ?? []), Number(record.values[valueField] ?? 0)]); }); return [...groups].map(([label, values]) => ({ label, value: Math.round(values.reduce((sum, value) => sum + value, 0) / values.length) })); }
